### ISSUE TITLE
Don't look if ADF output in cupid-webpage unless cupid-diagnostics ran the atm notebooks

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/CUPiD#160]
**Describe the bug**
When testing #159, I ran

```
$ cupid-diagnostics --land
$ cupid-webpage
```

and got

```
Traceback (most recent call last):
  File "${CONDA_ENVS}/cupid-infrastructure/bin/cupid-webpage", line 8, in <module>
    sys.exit(build())
             ^^^^^^^
  File "${CONDA_ENVS}/cupid-infrastructure/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "${CONDA_ENVS}/cupid-infrastructure/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "${CONDA_ENVS}/cupid-infrastructure/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "${CONDA_ENVS}/cupid-infrastructure/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "${CUPID_ROOT}/cupid/cupid_webpage.py", line 57, in build
    shutil.copytree(
  File "${CONDA_ENVS}/cupid-infrastructure/lib/python3.11/shutil.py", line 559, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './ADF_output'
```

**To Reproduce**
Run `cupid-diagnostics` for the `key_metrics` example on a subset of components that does not include the atmosphere, then run `cupid-webpage`

**Expected behavior**
Only try to copy output from the ADF if it exists (or maybe if we expect it to exist?)

**Comment by dabail10** [comment]
Similar issue with cupid-clean:

(cupid-infrastructure) [dbailey@derecho1 ~/CUPiD]> cupid-clean
ERROR: config.yml not found

**Comment by mnlevy1981** [comment]
@dabail10 the `cupid-clean` issue looks like you need to `cd examples/key_metrics` before running it. I don't think the clean command looks for ADF output
